### ISSUE TITLE
Models/Admin Todo

### ISSUE THREAD

**Issue by abkfenris** [abkfenris/baxter-flask#2]
Models/Admin
- [ ] Admin Index #10 
- [ ] User #4
- [ ] Weather Index #5
  - [x] Weather Observation #6
    - [ ] Photos
  - [x] Weather Forecast #7
    - [ ] Weather Observation
    - [ ] Avalanche Discussion
    - [ ] Conditions Discussion
    - [ ] Photos
- [ ] Conditions Discussion #8 
  - [ ] Photos
- [ ] Geospatial Index #9 
  - [x] Trails #11
    - [ ] Photos
    - [ ] Condition
    - [ ] Maintenance
  - [x] Points of Interest #12
    - [ ] Photos
    - [ ] Maintenance
  - [ ] Ski/Climb routes #13
    - Should they just be trails with more info about them?
  - [ ] Roads #14
    - [ ] Photos
    - [ ] Maintenance
  - [ ] Campsites #15
    - [ ] Photos
    - [ ] Maintenance
  - [ ] Maintenance
- [ ] Snow #17 
  - [x] Avalanche Path #20
    - [ ] Photos
  - [x] Avalanche Incidents #21
    - [x] Photos - can upload, but not retrieve the correct url
    - [x] Snow Pits
    - [ ] Avalanche Problems
  - [ ] Avalanche Discussion #22
    - [ ] Snow Observations
    - [ ] Photos
  - [x] Snow Pits #18
    - [ ] Photos
  - [ ] Snow Observation #23
    - [ ] Snow Pits
    - [ ] Photos
    - Should Snow Observations just be weather observations?trying to manually right a list
  - [ ] AvalancheInvolved #24
  - [ ] AvalancheProblems #19
  - [ ] AvalancheProblemsDaily - many-to-many for Avalanche Discussions
- [ ] Photos #3
